import express from "express";
import Bottle from "../models/Bottle.js";
const router = express.Router();
router.post("/", async (req,res)=>{try{const p={...req.body,barcode:String(req.body.barcode||"").trim(),brandName:String(req.body.brandName||"").trim(),productId:String(req.body.productId||"").trim(),bottleSizeML:Number(req.body.bottleSizeML||750),emptyBottleWeightG:Number(req.body.emptyBottleWeightG||400),costPrice:Number(req.body.costPrice||0),sellingPrice:Number(req.body.sellingPrice||0)};if(!p.barcode||!p.brandName)return res.status(400).json({message:"Barcode and Brand Name required"});if(await Bottle.findOne({barcode:p.barcode}))return res.status(409).json({message:"Bottle with this barcode already exists"});res.status(201).json({message:"Bottle added",bottle:await Bottle.create(p)});}catch(e){res.status(400).json({message:e.message});}});
router.get("/", async (req,res)=>{try{const s=req.query.search;const f=s?{$or:[{barcode:{$regex:s,$options:"i"}},{productId:{$regex:s,$options:"i"}},{brandName:{$regex:s,$options:"i"}},{category:{$regex:s,$options:"i"}}]}:{};res.json(await Bottle.find(f).sort({createdAt:-1}));}catch(e){res.status(500).json({message:e.message});}});
router.get("/:barcode", async (req,res)=>{try{const b=await Bottle.findOne({barcode:String(req.params.barcode).trim()});if(!b)return res.status(404).json({message:"Bottle not found"});res.json(b);}catch(e){res.status(500).json({message:e.message});}});
router.put("/:id", async (req,res)=>{try{const b=await Bottle.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true});if(!b)return res.status(404).json({message:"Bottle not found"});res.json({message:"Bottle updated",bottle:b});}catch(e){res.status(400).json({message:e.message});}});
router.delete("/:id", async (req,res)=>{try{const b=await Bottle.findByIdAndDelete(req.params.id);if(!b)return res.status(404).json({message:"Bottle not found"});res.json({message:"Bottle deleted"});}catch(e){res.status(500).json({message:e.message});}});
export default router;
