import express from "express";
import Bottle from "../models/Bottle.js";
import Stock from "../models/Stock.js";
import Movement from "../models/Movement.js";
const router = express.Router();
const stockValue=(cost,full,size,ml)=>Math.round(Number(cost||0)*Number(full||0)+Number(cost||0)*(Number(ml||0)/Math.max(Number(size||1),1)));
async function addStock(bottle,outlet,location,full,open,ml){let s=await Stock.findOne({barcode:bottle.barcode,outlet,location});if(s){s.fullBottles+=Number(full||0);s.openBottles+=Number(open||0);s.openBottleML+=Number(ml||0);s.stockValue=stockValue(s.costPrice,s.fullBottles,s.bottleSizeML,s.openBottleML);await s.save();return s;}return Stock.create({bottle:bottle._id,productId:bottle.productId,barcode:bottle.barcode,brandName:bottle.brandName,category:bottle.category,bottleSizeML:bottle.bottleSizeML,emptyBottleWeightG:bottle.emptyBottleWeightG,costPrice:bottle.costPrice,outlet,location,fullBottles:Number(full||0),openBottles:Number(open||0),openBottleML:Number(ml||0),stockValue:stockValue(bottle.costPrice,full,bottle.bottleSizeML,ml)});}
router.get("/",async(req,res)=>{try{const f={};if(req.query.outlet)f.outlet=req.query.outlet;if(req.query.location)f.location=req.query.location;res.json(await Stock.find(f).sort({updatedAt:-1}));}catch(e){res.status(500).json({message:e.message});}});
router.post("/assign",async(req,res)=>{try{const {barcode,toOutlet,toLocation,quantityFull=0,quantityOpen=0,openBottleML=0,note=""}=req.body;if(!barcode||!toOutlet||!toLocation)return res.status(400).json({message:"Barcode, outlet and location required"});const bottle=await Bottle.findOne({barcode:String(barcode).trim()});if(!bottle)return res.status(404).json({message:"Bottle not found in database"});const stock=await addStock(bottle,toOutlet,toLocation,quantityFull,quantityOpen,openBottleML);const movement=await Movement.create({type:"ASSIGN",barcode:bottle.barcode,productId:bottle.productId,brandName:bottle.brandName,category:bottle.category,toOutlet,toLocation,quantityFull,quantityOpen,openBottleML,note});res.status(201).json({message:"Stock assigned",stock,movement});}catch(e){res.status(400).json({message:e.message});}});
router.post("/transfer",async(req,res)=>{try{const {barcode,fromOutlet,fromLocation,toOutlet,toLocation,quantityFull=0,quantityOpen=0,openBottleML=0,note=""}=req.body;const source=await Stock.findOne({barcode:String(barcode).trim(),outlet:fromOutlet,location:fromLocation});if(!source)return res.status(404).json({message:"Source stock not found"});const qf=Number(quantityFull||0),qo=Number(quantityOpen||0),qml=Number(openBottleML||0);if(source.fullBottles<qf)return res.status(400).json({message:"Not enough full bottles"});if(source.openBottles<qo)return res.status(400).json({message:"Not enough open bottles"});if(source.openBottleML<qml)return res.status(400).json({message:"Not enough open ML"});source.fullBottles-=qf;source.openBottles-=qo;source.openBottleML-=qml;source.stockValue=stockValue(source.costPrice,source.fullBottles,source.bottleSizeML,source.openBottleML);await source.save();const bottle=await Bottle.findOne({barcode:source.barcode});const dest=await addStock(bottle,toOutlet,toLocation,qf,qo,qml);const movement=await Movement.create({type:"TRANSFER",barcode:source.barcode,productId:source.productId,brandName:source.brandName,category:source.category,fromOutlet,fromLocation,toOutlet,toLocation,quantityFull:qf,quantityOpen:qo,openBottleML:qml,note});res.json({message:"Stock transferred",source,destination:dest,movement});}catch(e){res.status(400).json({message:e.message});}});
router.get("/movements/history",async(_,res)=>{try{res.json(await Movement.find().sort({createdAt:-1}).limit(500));}catch(e){res.status(500).json({message:e.message});}});
export default router;
